empire_cb:
	./build_config.py INIT_EMPIRE_CB_TEMPLATE.txt CB_MAPS_INIT.txt
empire_bt:
	./build_config.py INIT_EMPIRE_BT_TEMPLATE.txt ALL_MAPS_INIT.txt
bagner:
	./build_config.py INIT_BAGNER_TEMPLATE.txt ALL_MAPS_INIT.txt
test:
	./build_config.py INIT_TEST_TEMPLATE.txt ALL_MAPS_INIT.txt
